name: Build Torrent Trackers Domains List
on:
  workflow_dispatch:
  schedule:
    - cron: "59 23 * * 2,6"
jobs:
  build-torrent-trackers-domains-list:
    runs-on: ubuntu-slim
    steps:
      - name: Check out repository code
        uses: actions/checkout@v6
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Get trackers_all.txt & Update torrent_trackers_domains.txt
        run: |
          url=https://raw.githubusercontent.com/ngosang/trackerslist/refs/heads/master/trackers_all.txt
          trackers_all_sha256sum=$(curl -fsSL "$url" | tee ${{ runner.temp }}/trackers_all.txt | sha256sum | awk '{print $1}')
          echo "trackers_all_sha256sum=$trackers_all_sha256sum"
          if [[ "$trackers_all_sha256sum" == $(cat trackers_all_sha256sum.txt) ]]; then
            echo 'should_commit=false' | tee -a "$GITHUB_ENV"
            echo 'trackers_all.txt not changed; nothing to do'
            exit 0
          fi
          echo 'should_commit=true' | tee -a "$GITHUB_ENV"
          echo 'trackers_all.txt changed; will update torrent_trackers_domains.txt'
          echo "$trackers_all_sha256sum" > trackers_all_sha256sum.txt
          # sed "/^$/d" ${{ runner.temp }}/trackers_all.txt | cut -d":" -f2 | cut -d"/" -f3
          awk -F':' 'NF {split($2, a, "/"); print a[3]}' ${{ runner.temp }}/trackers_all.txt > torrent_trackers_domains.txt

      - name: Commit changes
        uses: EndBug/add-and-commit@v10
        if: ${{ env.should_commit == 'true' }}
        with:
          default_author: github_actions
          add: |
            - trackers_all_sha256sum.txt
            - torrent_trackers_domains.txt

